#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sys import argv

def main(env='dev', host=None, port=None):

    # set configuration
    import config
    config.config = config.configs[env]  # with the right environment

    # set flask instance
    from utils import get_app
    import api
    api.app = get_app()

    # load modules
    from api.utils import import_modules
    import_modules('api')

    # technical setup

    # database setup
    from api.db import db
    db.create_all()

    # start the server
    if env == 'prod' and host is None:
        host = '0.0.0.0'

    api.app.run(host=host, port=port)


if __name__ == '__main__':

    from sys import argv

    main(*argv[1:])
