# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('model', models.CharField(max_length=500)),
                ('data_id', models.BigIntegerField()),
                ('comment', models.CharField(max_length=1024)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('name', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StateRequest',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.CRUD'),
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_requests.StateRequest'),
        ),
    ]
