# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='answer',
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='answer_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
