# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_requests', '0002_auto_20160924_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountrequest',
            old_name='date',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='accountrequest',
            old_name='model',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='accountrequest',
            old_name='data_id',
            new_name='srcmodelid',
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='srcmodel',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='targetmodel',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrequest',
            name='targetmodelid',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
